image: python:3.10
pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install pipenv
            - pipenv install -d
            - pipenv run pytest --cov
      - step:
          name: Lint code
          script:
            # Enforce style consistency across projects
            - pip install black
            - black .
  branches:
    master:
      - step:
          name: Build Image
          image: atlassian/default-image:3
          script:
            - IMAGE_NAME=$BITBUCKET_REPO_SLUG
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: $BITBUCKET_REPO_SLUG
                TAGS: $BITBUCKET_COMMIT
          services:
            - docker
          caches:
            - docker


