definitions:
  steps:
    - step: &Test-Step
        name: Test
        caches:
          - pip
        script:
          - pip install pipenv
          - pipenv install -d
          - pipenv run pytest --cov
    - step: &Lint-Step
        name: Lint code
        script:
          # Enforce style consistency across projects
          - pip install black
          - black .

image: python:3.10
pipelines:
  default:
    - parallel:
      - step: *Test-Step
      - step: *Lint-Step
  branches:
    master:
      - parallel:
          - step: *Test-Step
          - step: *Lint-Step
      - step:
          name: Build Image
          image: atlassian/default-image:3
          script:
            - docker build . --file Dockerfile --tag "pokemon"
            - pipe: atlassian/aws-ecr-push-image:1.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: "pokemon"
                TAGS: $BITBUCKET_COMMIT
          services:
            - docker
          caches:
            - docker
